# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-07 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('isActive', models.BooleanField(default=False, verbose_name='是否激活')),
                ('phone', models.BigIntegerField(verbose_name='手机号码')),
                ('code', models.IntegerField(verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name_plural': '注册表',
                'db_table': 'user_regist',
            },
        ),
        migrations.CreateModel(
            name='WeiboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuid', models.CharField(db_index=True, max_length=50, verbose_name='微博用户ID')),
                ('access_token', models.CharField(max_length=100, verbose_name='授权令牌')),
                ('uid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserRegist')),
            ],
            options={
                'verbose_name_plural': '微博用户表',
                'db_table': 'weibo_user',
            },
        ),
    ]
