# Generated by Django 3.2.7 on 2021-10-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commnuity_user', models.IntegerField(verbose_name='发表文章用户')),
                ('lable', models.CharField(max_length=100, verbose_name='文章标签')),
                ('commnuit_content', models.TextField(verbose_name='文章内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('click_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('commnuit_img', models.ImageField(blank=True, upload_to='', verbose_name='文章图片')),
                ('comment_num', models.IntegerField(default=0, verbose_name='文章评论数')),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='CommnuityLable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable_name', models.CharField(max_length=20, verbose_name='论坛标签名')),
                ('img_url', models.ImageField(blank=True, upload_to='', verbose_name='标签默认图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_user', models.IntegerField(verbose_name='评论用户')),
                ('commented_user', models.IntegerField(verbose_name='被评论用户')),
                ('content', models.CharField(max_length=500, verbose_name='评论内容')),
                ('comment_subid', models.CharField(max_length=100, verbose_name='子级评论')),
                ('comment_pid', models.CharField(max_length=100, verbose_name='父级评论')),
                ('is_primery', models.IntegerField(default=1, verbose_name='是否是一级评论')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.article', verbose_name='所属文章')),
            ],
        ),
    ]
