# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-08 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityparticipant',
            old_name='user',
            new_name='join_user',
        ),
    ]
