# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-26 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0002_auto_20191226_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='portrait',
            field=models.ImageField(default='boy1.jpg.png', upload_to='ICClub/static/images/userhead/', verbose_name='头像路径'),
        ),
    ]
