# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-08 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0002_auto_20201108_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityparticipant',
            old_name='join_user',
            new_name='user',
        ),
    ]
