# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-26 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0003_auto_20191226_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='act_img',
            field=models.ImageField(default=None, upload_to='images/activity/', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='adminarticle',
            name='act_img',
            field=models.ImageField(default=None, upload_to='images/official/', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='interesttag',
            name='img_url',
            field=models.ImageField(null=True, upload_to='images/label/', verbose_name='默认图片'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='portrait',
            field=models.ImageField(default='boy1.jpg.png', upload_to='images/userhead/', verbose_name='头像路径'),
        ),
    ]
