# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-17 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0003_auto_20201108_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activ_address',
            field=models.CharField(default=None, max_length=100, verbose_name='活动地点'),
        ),
    ]
