# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-26 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0004_auto_20191226_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='portrait',
            field=models.ImageField(default='images/userhead/boy1.jpg', upload_to='images/userhead/', verbose_name='头像路径'),
        ),
    ]
