# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0005_auto_20191226_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='interest',
            field=models.ManyToManyField(default=None, to='activ.InterestTag', verbose_name='爱好标签'),
        ),
    ]
