# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-11-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0006_auto_20191227_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminarticle',
            name='tag_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activ.InterestTag', verbose_name='活动标签'),
        ),
    ]
