# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-12-26 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0005_auto_20191226_1313'),
        ('users', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=320, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('review_id', models.IntegerField(default=0, verbose_name='被回复的评论id')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.AdminArticle', verbose_name='所属文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserRegist', verbose_name='评论/回复人')),
            ],
            options={
                'verbose_name_plural': '公告文章评论',
                'db_table': 'article_comment',
            },
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='review_id',
            field=models.IntegerField(default=0, verbose_name='被回复的评论id'),
        ),
    ]
